services:
  fastapi_server:
    image: fastapi-swarm-test
    # build: .
    # container_name: fastapi_container
    ports:
    - target: ${APP_PORT:-8000}
      published: ${APP_PORT:-8000}
      protocol: tcp
      mode: host
    environment:
      APP_PORT: ${APP_PORT:-8000}