services:
  fastapi_server:
    image: ${REGISTRY:-}${REGISTRY:+/}fastapi-swarm-test
    build: .
    ports:
    - target: ${APP_PORT:-8000}
      published: ${APP_PORT:-8000}
      protocol: tcp
      mode: host
    environment:
      APP_PORT: ${APP_PORT:-8000}